-- Очищаем таблицы
DELETE FROM LINK_FILMLIKES;
DELETE FROM LINK_FILMGENRE;
DELETE FROM FRIENDSHIPS;
DELETE FROM FILMS;
DELETE FROM USERS;

-- Сбрасываем ID
ALTER TABLE USERS ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE FILMS ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE LINK_FILMLIKES ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE LINK_FILMGENRE ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE FRIENDSHIPS ALTER COLUMN ID RESTART WITH 1;

-- Словари
MERGE INTO DICT_MPA (id, name) VALUES
    (1, 'G'),
    (2, 'PG'),
    (3, 'PG-13'),
    (4, 'R'),
    (5, 'NC-17');

MERGE INTO DICT_FILMGENRES (id, name) VALUES
    (1, 'Комедия'),
    (2, 'Драма'),
    (3, 'Мультфильм'),
    (4, 'Триллер'),
    (5, 'Документальный'),
    (6, 'Боевик');

MERGE INTO DICT_FRIENDSHIPTYPE (id, name) VALUES
    (1, 'Подтвержденная'),
    (2, 'Неподтвержденная');